### PR TITLE
Expose close, close_in and close_out in Cohttp_lwt

### PR DESCRIPTION
**Pull request by samoht**

### CODE REVIEW

**Comment by samoht** [comment]
wait before merging, seems that other type constraints are missing (between Request.IO.oc and IO.oc). Not sure that's expected.

**Comment by samoht** [comment]
Seems to work ok with both patches (and this gives a much nicer user interface). Would maybe make sense to make the close function into the IO signature though.

**Comment by avsm** [comment]
Need to check on reverse dependencies to see what this breaks

**Comment by samoht** [comment]
ok testing this. I'm not sure people are writing fancy functor for cohttp though (the existing one are already fancy enough :p)

**Comment by samoht** [comment]
seems that it doesn't break more than `0.16.0` already does:

```
| bt | camlp4<4.02.0+system is not available because your system doesn't comply with !preinstalled & ocaml-version = "4.02.0". |
| cowabloga | ok |
| dog| ok |
| facebook-sdk | facebook-sdk -> cohttp < 0.16.0 |
| github | ok |
| imaplet-lwt | doesn't compile with latest irmin |
| iocaml | ok |
| irmin | ok |
| merge-queues | merge-queues -> irmin = 0.8.3 -> cohttp < 0.16.0 |
| merge-ropes| merge-ropes -> irmin = 0.8.3 -> cohttp < 0.16.0 |
| message-switch | message-switch -> cohttp < 0.16.0 |
| mirage-http | ok |
| mirage-http-unix | Conflicting version constraints for base64 and mirage-net-unix |
| mirage-http-xen | mirage-xen is not available because your OS doesn't match = linux |
| mirage-www | cow<1.0.0 is not available because it requires OCaml < 4.02.0 |
| ojs-base | ok |
| opam-publish | doesn't compile because name-clash between ctypes and dose's `Common` |
| opam-sync-github-prs | ok |
| opium | ok |
| slacko | ok |
| sociaml-facebook-api | ok |
| sociaml-oauth-client | sociaml-oauth-client -> cohttp < 0.16.0 |
| sociaml-tumblr-api | sociaml-tumblr-api -> sociaml-oauth-client < 0.5.0 | sociaml-oauth-client >= 0.5.0 -> cohttp < 0.16.0 |
| vhd-tool | tls.0.3.0 is in conflict with vhd-tool.0.7.6 |
| websocket | ok |
| xapi | cdrom is not available because your OS doesn't match = linux. |
| xapi-forkexecd | xapi-forkexecd -> xapi-idl -> message-switch -> cohttp < 0.16.0 |
| xapi-idl | xapi-idl -> message-switch -> cohttp < 0.16.0 |
| xapi-networkd | xapi-libs-transitional is not available because your OS doesn't match = linux. |
| xapi-rrd-transport | xapi-rrd-transport -> xapi-idl -> message-switch -> cohttp < 0.16.0 |
| xapi-rrdd | xapi-libs-transitional is not available because your OS doesn't match = linux. |
| xapi-rrdd-plugin | xapi-libs-transitional is not available because your OS doesn't match = linux.|
| xapi-squeezed | xapi-squeezed -> xapi-idl -> message-switch -> cohttp < 0.16.0 |
| xapi-tapctl | xapi-tapctl -> xapi-forkexecd -> xapi-idl -> message-switch -> cohttp < 0.16.0 |
| xapi-xenops-cli | xapi-xenops-cli -> xapi-idl -> message-switch -> cohttp < 0.16.0 |
| xapi-xenopsd | xapi-xenopsd -> xapi-idl >= 0.9.19 -> message-switch -> cohttp < 0.16.0|
| xe | ok |
| xe-unikernel-upload | ok |
| xen-api-client | ok |
```

**Comment by avsm** [comment]
Alright, I want that opam revdeps -> GitHub table script now too :)

**Comment by samoht** [comment]
It's unfortunately not a script yet ...

**Comment by avsm** [comment]
Where do you use this btw?  I was hoping to keep connection management separate from using the flow, as it's irrelevant to (e.g.) the String version.

**Comment by samoht** [comment]
Useful to build flows on top of cohttp response: https://github.com/samoht/ocaml-git/blob/3564b44ebe6133154cd35a706488b997194421c1/lib/http/git_http.ml#L61 that code doesn't really work yet, though, to that's maybe not totally necessary.

**Comment by samoht** [comment]
I need this to create flows on top of raw HTTP channels, using https://github.com/mirage/mirage-flow/blob/master/lib/fflow.mli#L30. Would be nice if it could be merged.

**Comment by samoht** [comment]
I'm fine to close this one for now on as I have workarounds.

**Pull request closed without merging**
