### PR TITLE
refactor: share bytebuffer between lwt/async

### PR DESCRIPTION
**Pull request by rgrinberg**
it's simple enough to share the two types

cc @anuragsoni

### CODE REVIEW

**Comment by anuragsoni** [comment]
This looks good to me.

**Comment by mseri** [comment]
Sorry I was late. I do agree with @anuragsoni (and well spotted for #899!)

**Comment by mseri** [comment]
I wonder why the eio tests are failing with this change though:
```
File "cohttp-eio/tests/test_chunk.t", line 1, characters 0-0:
/usr/bin/git --no-pager diff --no-index --color=always -u _build/.sandbox/418fa8dfc7986f69c6616f5b32af8b81/default/cohttp-eio/tests/test_chunk.t _build/.sandbox/418fa8dfc7986f69c6616f5b32af8b81/default/cohttp-eio/tests/test_chunk.t.corrected
diff --git a/_build/.sandbox/418fa8dfc7986f69c6616f5b32af8b81/default/cohttp-eio/tests/test_chunk.t b/_build/.sandbox/418fa8dfc7986f69c6616f5b32af8b81/default/cohttp-eio/tests/test_chunk.t.corrected
index a0bc7c2..2ee7937 100644
--- a/_build/.sandbox/418fa8dfc7986f69c6616f5b32af8b81/default/cohttp-eio/tests/test_chunk.t
+++ b/_build/.sandbox/418fa8dfc7986f69c6616f5b32af8b81/default/cohttp-eio/tests/test_chunk.t.corrected
@@ -5,6 +5,7 @@ Test chunk request processing.
   $ port=8081
   $ test-chunk-server -p ${port} &
+  Fatal error: exception Invalid_argument("close: file descriptor used after calling close!")
   $ running_pid=$!
   $ crlf << EOF | ncat localhost ${port}
   > POST / HTTP/1.1
@@ -52,3 +53,6 @@ Test chunk request processing.
    extensions: 
   $ kill ${running_pid}
+  /tmp/dune_cram_85c088_.test_chunk.t/main.sh: 1: kill: No such process
+  
+  [1]
File "cohttp-eio/tests/test_get_post.t", line 1, characters 0-0:
/usr/bin/git --no-pager diff --no-index --color=always -u _build/.sandbox/4176bcf4117a4afc40a2944886bde042/default/cohttp-eio/tests/test_get_post.t _build/.sandbox/4176bcf4117a4afc40a2944886bde042/default/cohttp-eio/tests/test_get_post.t.corrected
diff --git a/_build/.sandbox/4176bcf4117a4afc40a2944886bde042/default/cohttp-eio/tests/test_get_post.t b/_build/.sandbox/4176bcf4117a4afc40a2944886bde042/default/cohttp-eio/tests/test_get_post.t.corrected
index 71f0947..9e674fa 100644
--- a/_build/.sandbox/4176bcf4117a4afc40a2944886bde042/default/cohttp-eio/tests/test_get_post.t
+++ b/_build/.sandbox/4176bcf4117a4afc40a2944886bde042/default/cohttp-eio/tests/test_get_post.t.corrected
@@ -1,6 +1,7 @@
 Test GET success.
   $ test-server &
+  Fatal error: exception Invalid_argument("close: file descriptor used after calling close!")
   $ running_pid=$!
   $ crlf << EOF | ncat localhost 8080
   > GET /get HTTP/1.1
@@ -15,11 +16,15 @@ Test GET success.
   version: HTTP/1.1
   headers: Header {  }
   $ kill ${running_pid}
+  /tmp/dune_cram_0cc6d0_.test_get_post.t/main.sh: 1: kill: No such process
+  
+  [1]
 Test GET error.
 The test should respond with error message since we are trying to read request body. HTTP 1.1 doesn't support request bodies in GET.
   $ test-server &
+  Fatal error: exception Invalid_argument("close: file descriptor used after calling close!")
   $ running_pid=$!
   $ crlf << EOF | ncat localhost 8080
   > GET /get_error HTTP/1.1
@@ -31,10 +36,14 @@ The test should respond with error message since we are trying to read request b
   Request with HTTP method 'GET' doesn't support request body
   $ kill ${running_pid}
+  /tmp/dune_cram_0cc6d0_.test_get_post.t/main.sh: 1: kill: No such process
+  
+  [1]
 Test POST
   $ test-server &
+  Fatal error: exception Invalid_argument("close: file descriptor used after calling close!")
   $ running_pid=$!
   $ crlf << EOF | ncat localhost 8080
   > POST /post HTTP/1.0
@@ -53,5 +62,8 @@ Test POST
   hello world!
   $ kill ${running_pid}
+  /tmp/dune_cram_0cc6d0_.test_get_post.t/main.sh: 1: kill: No such process
+  
+  [1]
```

**Comment by mseri** [comment]
The failure is due to an issue in eio 0.3: see https://github.com/mirage/ocaml-cohttp/pull/886

**Pull request merged**
