### PR TITLE
add exn_hook to match conduit

### PR DESCRIPTION
**Pull request by vbmithr**
To be merged after https://github.com/mirage/ocaml-conduit/pull/181 is merged.

### CODE REVIEW

**Comment by hcarty** [comment]
This would provide a cleaner workaround path for #511 until a full/proper fix is added.

**Comment by vbmithr** [comment]
@rgrinberg @yomimono @talex5 ping? I think this should be merged now.

**Comment by yomimono** [comment]
I forgot about this because of the Conduit patch it presupposes, which is now merged.  It looks fine to me.

**Comment by SGrondin** [comment]
This feature has been a godsend, thank you!

**Pull request merged**
