### PR TITLE
Update to the newest Mirage_kv.RO API

### PR DESCRIPTION
**Pull request by samoht**
Update to the interface defined in https://github.com/mirage/mirage-kv/pull/14

### CODE REVIEW

**Comment by samoht** [comment]
Not yet.

**Comment by mseri** [comment]
```
[ERROR] No solution for cohttp-mirage: The following dependencies couldn't be met:
          - cohttp-mirage -> mirage-conduit >= 3.0.0 -> mirage-dns >= 3.0.0 -> mirage-kv-lwt < 2.0.0
          - cohttp-mirage -> mirage-kv-lwt >= 2.0.0
        Your request can't be satisfied:
          - No available version of mirage-kv-lwt satisfies the constraints
```

**Comment by hannesm** [comment]
@mseri indeed, it looks like we first need to get https://github.com/mirage/ocaml-dns/pull/156 released :)

**Comment by hannesm** [comment]
mirage-dns is now PRed to opam-repository at https://github.com/ocaml/opam-repository/pull/13546 -- once this hits master, we can restart the failing jobs here and see :)

**Comment by hannesm** [comment]
I restarted the failing travis builds now that mirage-dns is merged in opam-repository. They all work, though I removed the 4.04.0 cohttp-mirage build (mirage-kv 2.0.0 requires ocaml 4.05.0), and constrained cohttp-mirage to 4.05.0 -- but travis still runs this job and fails. imho good to merge (and a timely release of cohttp-mirage would unblock our mirage 3.5.0 release). thanks! :D

**Comment by mseri** [comment]
Do we just need to release cohttp-mirage?

**Comment by hannesm** [comment]
@mseri yes, cohttp-mirage release is sufficient. thanks!

**Comment by mseri** [comment]
@hannesm done: https://github.com/ocaml/opam-repository/pull/13560

**Pull request merged**
