### PR TITLE
Rename mirage-http to cohttp-mirage

### PR DESCRIPTION
**Pull request by rgrinberg**
Consistency with other libraries

### CODE REVIEW

**Comment by avsm** [comment]
Not yet -- we need to coordinate this with all the other renames (there are various PRs floating around that need to be combined and then a new release of mirage/mirage done to account for the new names)

**Comment by rgrinberg** [comment]
OK. Feel free to take over this effort.

**Comment by avsm** [comment]
I'll coordinate these...

**Comment by djs55** [comment]
I think we need to release `cohttp` soon -- the released version doesn't build with OCaml 4.06 (fix is in master).

I've made a change to the `mirage` tool and will try to make the CI pass (probably require some PINs). Assuming I get the `mirage` tool building, is there anything else needed before merging this and tagging 1.0.0?

**Comment by avsm** [comment]
nothing else except `mirage` tool I believe...

**Pull request merged**
