### PR TITLE
Use the latest Uri_sexp interfaces in uri.2.0.0

### PR DESCRIPTION
**Pull request by avsm**
see https://github.com/mirage/ocaml-uri/pull/124

### CODE REVIEW

**Comment by mseri** [comment]
Can you please update the opam files with `>= “2.0.0”` on uri?

**Comment by avsm** [comment]
done!

**Comment by mseri** [comment]
Thanks. Let’s wait for Travis and if it is good I merge

**Comment by mseri** [comment]
Argh. This cannot work until we release a new conduit with uri.2.0.0 support

**Comment by avsm** [comment]
woopsy, i'll look at that now

**Comment by avsm** [comment]
https://github.com/ocaml/opam-repository/pull/12830

**Comment by avsm** [comment]
Although there were no changes to conduit required for uri.2.0.0, which is a bit odd...

**Comment by mseri** [comment]
The lack of support for 4.03.0 is not unexpected, as `sexplib0` requires 4.04.1. The error message in that case is clear and we probably should not change the ocaml-version bounds on cohttp, as a future release supporting 4.03.0 could make it compatible again

@avsm unless you think changing the version is needed, I'd be happy to merge

**Pull request merged**
