### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### mirage/ocaml-cohttp now has a Chat Room on Gitter

@rgrinberg has just created a chat room. You can visit it here: [https://gitter.im/mirage/ocaml-cohttp](https://gitter.im/mirage/ocaml-cohttp?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/mirage/ocaml-cohttp?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by rgrinberg** [comment]
Hopefully nobody objects to me adding this. Gitter is pretty nice for hearing more from our users and possibly coordinating some development.

**Comment by amirmc** [comment]
I've seen this on some other repos and I'm curious to see how it goes. 

Best wishes,
Amir

--
sent via mobile

**Comment by dbuenzli** [comment]
Le vendredi, 13 mars 2015 à 21:12, Rudi Grinberg a écrit :
> Gitter is pretty nice for hearing more from our users and possibly coordinating some development.


I don't know what this is but it looks like (yet another) synchronous communication mean. In my opinion coordinating quality development is better done with asynchronous means of communication (a.k.a. mailing list).  

A mailing list archives (i.e. provides a way to reference), makes better arguments (because of the format), don't require people to be here when discussions happen (i.e. may give you more feedback on design choices) and is easier to ignore when you are trying to work. It may be slower and more involved but so is developing quality software.  

Daniel

**Comment by avsm** [comment]
> I don't know what this is but it looks like (yet another) synchronous communication mean. 

I'm actually pretty impressed by this, since its synchronous but persistent.  I logged in, read the backlog (which didn't have the usual terrible IRC S/N ratio) and learnt a bunch of interesting things about how Cohttp is being used.

**Comment by dbuenzli** [comment]
Le dimanche, 15 mars 2015 à 12:28, Anil Madhavapeddy a écrit :
>  its synchronous but persistent.

Indeed. But still too casual for my taste. Chat remains chat, whether persistant or not, it's a different medium. D

**Comment by rgrinberg** [comment]
I have nothing against mailing list but I do accept the fact that a large chunk of our users and contributors has no interest in using them. Gitter is just an attempt to reach out to them.

**Comment by amirmc** [comment]
My (somewhat lengthy) 2¢.

I think there are typically two things at play when discussions like this come up:

- Allowing many 'touch-points' for people to engage with a project
- Having a canonical place where decisions are made/visible/recorded

I am very much in favour of having lots of mechanisms for people to engage with projects (with the caveat that the maintainers can actually monitor them all).  It allows more incoming feedback and reduces friction for those who may already be familiar/registered with an existing service and I believe it generally helps to broaden the community.

However, it places a burden on others who simply want to keep up to date with things. It's unreasonable to expect users of a project to trawl all the possible communication methods to see where things stand or what direction the project is taking. For this, I think it's valuable to have one place that can be easily monitored by people who have an interest (and allow them to remain engaged). This may be a mailing list, issue-tracker, wiki page or something else and it's not always clear at first glance which of these is most important for any given project (assuming they all exist).

To help with this, I'd suggest some kind of notice in the README or a CONTRIBUTING file that makes it clearer where major discussions will take place. That way users can feel confident that they won't miss anything important without feeling that they have to track everything. Of course, this does mean the maintainers must both define something and then *stick* to it.  In the case of cohttp, it seems to me that the issue-tracker is the main place things are brought up, whereas Gitter is more of a chat mechanism (and I'm sure cohttp discussions also take place on IRC in the Mirage and OCaml rooms too). 

Anyway, those are my thoughts and I wanted to share. :)

**Pull request merged**
