### PR TITLE
Fix travis

### PR DESCRIPTION
**Pull request by mseri**
This should allow us to rely a bit more blindly on Travis, as there were some tests that were expected to fail and not all the recent compilers where tested.

### CODE REVIEW

**Comment by mseri** [comment]
There are two failure remaining, that I don't know how to solve:
```
[ERROR] The sources of the following couldn't be obtained, aborting:
          - ounit.2.0.8: Curl failed
```

Rerunning the two tests does not help

**Comment by samoht** [comment]
Use `alcotest`? :-)

More seriously, it's probably due to a network glitch..,

**Comment by mseri** [comment]
I had rerun the tests a handful of times between yesterday and today, but I think you have the right solution... time to add a commit to move to alcotest

**Comment by samoht** [comment]
Note also that you can remove the minor version, as the container have pre-build switches for the `4.0*` compilers (>= 4.03).

**Comment by mseri** [comment]
The port to alcotest of the remaining tests is a bit less straightforward than I envisioned. I suggest we keep it in a separate PR. I’l Uodate the minor version from the tests then I think it’s all for this PR

**Comment by mseri** [comment]
Should we merge this and/or prepare a new release? This should allow us to close some issues already

**Comment by avsm** [comment]
sgtm

**Pull request merged**
