### PR TITLE
allow setting withCredentials in XHR

### PR DESCRIPTION
**Pull request by zoggy**
This resolves https://github.com/mirage/ocaml-cohttp/issues/471 .

### CODE REVIEW

**Comment by rgrinberg** [comment]
Travis seems to be failing:

```
#=== ERROR while installing cohttp.0.20.2 =====================================#
# opam-version 1.2.2
# os           linux
# command      make PREFIX=/home/travis/.opam/system
# path         /home/travis/.opam/system/build/cohttp.0.20.2
# compiler     system (4.02.3)
# exit-code    2
# env-file     /home/travis/.opam/system/build/cohttp.0.20.2/cohttp-32633-1872ec.env
# stdout-file  /home/travis/.opam/system/build/cohttp.0.20.2/cohttp-32633-1872ec.out
# stderr-file  /home/travis/.opam/system/build/cohttp.0.20.2/cohttp-32633-1872ec.err
### stdout ###
# Error: This expression has type
# [...]
#            send_formData : Form.formData Js.t -> unit Js.meth;
#            setRequestHeader : Js.js_string Js.t ->
#                               Js.js_string Js.t -> unit Js.meth;
#            status : int Js.readonly_prop;
#            statusText : Js.js_string Js.t Js.readonly_prop;
#            upload : XmlHttpRequest.xmlHttpRequestUpload Js.t Js.optdef
#                     Js.readonly_prop >
#        It has no method withCredentials
# Command exited with code 2.
### stderr ###
```

**Comment by zoggy** [comment]
This depends on current master of js_of_ocaml, with this commit https://github.com/ocsigen/js_of_ocaml/commit/4014e6538f5d10a5e2baffaf0cd389a874d63d95 on March 22nd. Let's wait for a new js_of_ocaml release, then.

**Comment by rgrinberg** [comment]
OK thanks for figuring it out. We'll also need to bump the constraints as well once jsoo is released.

**Comment by vbmithr** [comment]
@rgrinberg : I'm not an expert here. Should this be merged?

**Comment by rgrinberg** [comment]
@vbmithr once the constraints are updated.

@zoggy would you mind adding a minimum jsoo version to the opam file?

**Comment by zoggy** [comment]
The opam file already indicates a conflict with jsoo < 2.8, which is fine since withCredentials property was introduced in jsoo 2.8.

**Comment by rgrinberg** [comment]
thanks @zoggy

**Pull request merged**
