### PR TITLE
Fix compilation with lwt 2.5.0

### PR DESCRIPTION
**Pull request by vbmithr**

### CODE REVIEW

**Comment by vbmithr** [comment]
To be merged after lwt 2.5.0 has made its way in the opam repository.

**Comment by dsheets** [comment]
Can `buffer_size` remain so that `16384` isn't repeated?

**Comment by vbmithr** [comment]
Were does this constant comes from btw ?

**Comment by vbmithr** [comment]
Ah yeah, 4 pages.

**Comment by avsm** [comment]
Yep, just a reasonable page multiple.

**Comment by rgrinberg** [comment]
@vbmithr Should you also fix the constraints in `opam`?

**Comment by mlin** [comment]
bump. `opam install lwt cohttp` is failing as of this morning...

https://github.com/ocaml/opam-repository/pull/4365
https://travis-ci.org/mlin/narcissome-beacon/builds/70516962

**Comment by dsheets** [comment]
ocaml/opam-repository#4427

Sorry about that.

**Comment by dsheets** [comment]
This PR also needs to update the cohttp opam pin file with the new constraint.

**Comment by dsheets** [comment]
Should be fixed in opam-repository now. Thanks for your report!

**Comment by rgrinberg** [comment]
Am I crazy to suggest using some preprocessing to make cohttp compatible with both older and newer lwt?

I really hate creating opam hell for everyone with this.

**Comment by vbmithr** [comment]
What's the problem exactly ? Older version of cohttp will not work with newer lwt versions, is there more issues ?

**Comment by rgrinberg** [comment]
The problem is we're making it difficult for people who depend on older versions of cohttp and newer versions of lwt and vice versa.

**Comment by vbmithr** [comment]
On 16/07/2015 15:36, Rudi Grinberg wrote:
> The problem is we're making it difficult for people who depend on older
> versions of cohttp and newer versions of lwt and vice versa.

Personally I would not add cruft in our code in order to accomodate such
use cases.

It should be enough that for each version of cohttp, you need a certain
range of versions of lwt.

**Comment by rgrinberg** [comment]
I agree it adds cruft but I wouldn't trivialize the use case. Giving our users a smooth upgrade path and keeping the range of compatibility wide for 2 very popular libraries on opam is useful and important IMO.

Putting it another way, w/e ugliness and time spent it would cost us to keep this compatibility, I'm sure it is dwarfed by the combined pain of our users.

I will merge this and amend the opam file however so at least users who want to use the latest lwt can use cohttp#master.

**Comment by rgrinberg** [comment]
Applied. Thanks @vbmithr

**Pull request closed without merging**
