### PR TITLE
Transfer_io: read until EOF when body size is unknown

### PR DESCRIPTION
**Pull request by Chris00**
Fixes https://github.com/mirage/ocaml-cohttp/issues/239

### CODE REVIEW

**Comment by rgrinberg** [comment]
This is good, thanks.

**Comment by avsm** [comment]
This also changes the default read chunk size from 16384 to 4096. Not sure it makes a difference, but worth noting.

**Comment by Chris00** [comment]
I did some (quick nonscientific) testing and, if anything, it seems to be faster (IIRC, 4k is the right amount for disk IO according to “Programmation système en OCaml”).  I though it would put less pressure on the GC.

**Comment by avsm** [comment]
Values greater than 2k (256 words) get allocated directly onto the major heap, so I actually wonder if reading just below that threshold would keep the majority of such buffers in the minor heap.

**Comment by Chris00** [comment]
On Mon, 26 Jan 2015 06:47:05 -0800, Anil Madhavapeddy wrote:
> 
> Values greater than 2k (256 words) get allocated directly onto the major heap, so I actually wonder if reading just below that threshold would keep the majority of such buffers in the minor heap.

OK.  I think it is better to try using read with a byte buffer before optimizing its size.

**Pull request merged**
