### PR TITLE
Add more OCaml variants to GitHub Actions workflow

### PR DESCRIPTION
**Pull request by smorimoto**

### CODE REVIEW

**Comment by mseri** [comment]
Can you rebase this on master? I'd like to check that it succeeds before merging it

**Comment by mseri** [comment]
async does not run on win32 afaik. In this case we should avoid building in on the make win32 target, but maybe I am wrong

**Comment by mseri** [comment]
Can we avoid testing async on windows (not compatible) and js_of_ocaml on multicore (not available) ?

**Comment by smorimoto** [comment]
I found this not very useful at this point, so I close this once, but do this after switching to better packaging.

**Pull request closed without merging**
