### PR TITLE
dune: upgrade to dune lang 3.4 so that we can use mdx 0.2

### PR DESCRIPTION
**Pull request by bikallem**
I am in the process of converting cohttp-eio tests to using eio mocks so that tests involving networks and clocks are reliable. For that I need  `mdx 0.2` and hence dune 3.0 and above. This PR upgrades dune lang to 3.0. 

https://dune.readthedocs.io/en/latest/dune-files.html#mdx-since-2-4

~~Additionally, I have added myself to the authors.~~ EDIT: It seems the authors section in dune-project is replicated to all packages rather than just cohttp-eio, so this is reverted now.

### CODE REVIEW

**Comment by mseri** [comment]
Let me get the alpha release out first. There is an important outstanding issue in how we run some tests but once that is fixed, I think it can be completed

**Comment by bikallem** [comment]
@mseri Could we merge this now that alpha0 is out?

**Comment by mseri** [comment]
Can you rebase? With the templates the opam files will likely be different (and the templates may need some small adjustments with dune 3)

**Comment by bikallem** [comment]
> Can you rebase and rebuild the opam files? With the templates the opam files will likely be different (and the templates may need some small adjustments with dune 3)

Done.

**Comment by bikallem** [comment]
ci failing for cohttp-eio due to connection being reset. Could we restart it again, please?

**Comment by mseri** [comment]
nix is trying to install the wrong dune, do you by chance know how to update the file with opam2nix?

**Comment by mseri** [comment]
Thanks a lot. One last change: the `.opam.template` files need to be changed as follows:
```diff
build: [
  ["dune" "subst"] {dev}
  [
    "dune"
    "build"
    "-p"
    name
    "-j"
    jobs
-    "--promote-install-files=false"
    "@install"
    "$pkg/@runtest" {with-test} # this will be different, don't modify it
    "@doc" {with-doc}
  ]
-  ["dune" "install" "-p" name "--create-install-files" name]
]
```

**Comment by bikallem** [comment]
@mseri nix workflow is failing due to this (https://github.com/timbertson/opam2nix/pull/88)

**Comment by mseri** [comment]
Thanks

**Pull request merged**
