### PR TITLE
Update for Eio 0.7

### PR DESCRIPTION
**Pull request by talex5**
(once https://github.com/ocaml/opam-repository/pull/22619 is merged)

/cc @bikallem

### CODE REVIEW

**Comment by bikallem** [comment]
Oops. Sorry I didn't see this before opening mine (https://github.com/mirage/ocaml-cohttp/pull/954). That one has a one more commit (https://github.com/mirage/ocaml-cohttp/pull/954/commits/cfbbe49febeab514a21296083942e067598b3ba4) than this one.

**Comment by mseri** [comment]
Was https://github.com/mirage/ocaml-cohttp/commit/cfbbe49febeab514a21296083942e067598b3ba4 needed as well?

**Comment by bikallem** [comment]
Not strictly necessary but nice to have, I think. Perhaps cherry pick it?

**Comment by talex5** [comment]
> Not strictly necessary but nice to have, I think. Perhaps cherry pick it?

What's the advantage of cfbbe49febeab? The new code is a little longer. Is it faster? I would have thought that allocating the Failure exception wouldn't be any quicker than allocating an empty string, and installing an exception handler on the normal path would be a little slower?

**Comment by bikallem** [comment]
> What's the advantage of https://github.com/mirage/ocaml-cohttp/commit/cfbbe49febeab514a21296083942e067598b3ba4? The new code is a little longer. Is it faster? I would have thought that allocating the Failure exception wouldn't be any quicker than allocating an empty string, and installing an exception handler on the normal path would be a little slower?

I haven't done any bench-marking to verify if using exception handling is faster than allocation. However, my reasoning for the change is that exception handler in OCaml is very fast (since it is a register in a stack) and the overhead of a handler is that of a function call. Secondly, the code before was allocating an extra string in every call to `token`. This by itself is not much of an issue. However `token` is used quite a lot in the hot path (request parsing) - httips://github.com/mirage/ocaml-cohttp/blob/master/cohttp-eio/src/rwer.ml#L38, so therefore it is of some consequence if we can minimize allocation here. 

1. https://stackoverflow.com/questions/8564025/ocaml-internals-exceptions
2. https://stackoverflow.com/questions/12160390/ocaml-performance-of-exceptions

**Comment by talex5** [comment]
I suggest merging this as-is, as it fixes the compiler warning.

The other change can happen in a separate PR if it turns out to be useful.

**Pull request merged**
