### PR TITLE
Copy basic auth from Uri.userinfo into Authorization header

### PR DESCRIPTION
**Pull request by vklquevs**
I have been wondering the best place for this for a while -- it seems to me like this form of credentials is a common enough case to warrant being here.

This will take e.g. `user:pass` from `http://user:pass@host` and add it to the headers as basic authorization, without overriding any credentials in the supplied headers. It also only works with `user:pass`, not just `user`.

### CODE REVIEW

**Comment by dsheets** [comment]
LGTM. I've made a note to actually expose the username/password combo at mirage/ocaml-uri#62. Sorry about this old interface. :-/ @rgrinberg, comments?

**Comment by rgrinberg** [comment]
I think this is good as well but I'm not sure whether not overriding the header is the right behavior. In any case, this is better than not supporting it all.

**Comment by vklquevs** [comment]
I wasn't sure for a while either, but figured it might work better this way round for something along the lines of `wget user@host --ask-password`.

**Comment by rgrinberg** [comment]
Looks good to me. Merging this in and this should be slated for 0.16

@vklquevs for future reference, have a look at https://github.com/OCamlPro/ocp-indent for formatting your code.

**Comment by vklquevs** [comment]
Good stuff, & noted - it's time to stop awkwardly fighting with vim's default indentation!

**Pull request merged**
