### PR TITLE
release v3.1.0

### PR DESCRIPTION
**Pull request by samoht**

### CODE REVIEW

**Comment by samoht** [comment]
@mseri anything else to include in the 3.1 release?

**Comment by mseri** [comment]
Would be nice to include https://github.com/mirage/ocaml-cohttp/pull/747
I can take some time to make he V1/V2 change tomorrow

**Comment by samoht** [comment]
As there are still a few design issue to be resolved on #747 do you mind if I make a 3.1.0 release without these?

**Comment by mseri** [comment]
If we will really make #747 backward compatible, I'd say go ahead.
Otherwise, since this is a new major release and #747 is a nice clean-up, maybe it is worth waiting a few more days to see if we can smoothen those out and eventually include its breaking change in this release.

We could see how it evolves for this week and say that if it is too unclear on Monday next week we merge and release

**Comment by mseri** [comment]
Hi @samoht, while we wait for #747, I think we could also add https://github.com/mirage/ocaml-cohttp/pull/754 (or the alternative suggested there) in the new release

**Comment by samoht** [comment]
Closing this one as the CHANGELOG changes are tracked by #758

**Pull request closed without merging**
