### PR TITLE
Add more request URI tests for URI components

### PR DESCRIPTION
**Pull request by dsheets**
These are tests that I should have written before. Several fail (see #308).

### CODE REVIEW

**Comment by dsheets** [comment]
This is still not [RFC 2616 Sec 5.1.2](http://tools.ietf.org/html/rfc2616#section-5.1.2) compliant. Absolute URIs are allowed in the `Request-URI` production for proxies and does not indicate a path-like-URI. `authority` alone and `*` are also allowed for special methods. Servers should return the right error codes when these failures occur.

Compliance may require larger refactoring.

**Comment by dsheets** [comment]
I believe this is a reasonable implementation now.

**Comment by dsheets** [comment]
I added `CONNECT` and `TRACE` HTTP 1.1 standard methods and then used them to manage the parsing of the `CONNECT authority` request line which is ambiguous otherwise. I also tested `OPTIONS *` and ensured that the requested URI's path component is never empty.

**Comment by dsheets** [comment]
@samoht oops. I've changed the generate.ml script now. Thanks!

**Comment by rgrinberg** [comment]
Sorry, it's too much to review closely. Are there any breaking changes?

**Comment by dsheets** [comment]
I believe adding `CONNECT` and `TRACE` may be breaking if you rely on exhaustive method matches. Everything else should be correctness improvements.

**Comment by dsheets** [comment]
I believe I have addressed any outstanding issues. `*` is now handled correctly, non absolute paths now result in ``` `Invalid``` values from the parser. Directory traversal is handled directly in the parser.

**Comment by dsheets** [comment]
With no objections, I am merging this so we can release a version of cohttp that isn't horribly broken.

**Comment by avsm** [comment]
+1

**Pull request merged**
