### PR TITLE
cohttp-eio(client): call Buf_write.flush() after serializing request

### PR DESCRIPTION
**Pull request by bikallem**
Required for https://github.com/mirage/ocaml-cohttp/pull/948

### CODE REVIEW

**Comment by talex5** [comment]
Why is this needed/useful? What happens without it?

I would guess this will slow pipelined requests down a bit. Is it for back-pressure (we probably need to add some support for that in Buf_write itself)? It might also improve performance to hint to the system that this is a good place to flush, but that might be better done with `Fiber.yield` (which doesn't require everything to be flushed before continuing).

**Comment by bikallem** [comment]
> Why is this needed/useful? What happens without it?

Strictly not necessary or needed. `Client.get/post/head/delete` calls works correctly without flushing. This PR mostly improves individual request/response latency by calling `Buf_write.flush()` after it completes serializing the request. I noticed this while working on https://github.com/mirage/ocaml-cohttp/pull/948. In the client tests there the reading part (server response from mock socket) was done even before request was written to the socket. 

Is request pipelining a more normal usage and something that we want to optimize for? 

Perhaps an optional parameter `?flush` with default value of `false` to `Client.call` can cater to both use-cases well?

**Comment by talex5** [comment]
> Is request pipelining a more normal usage and something that we want to optimize for?

The wrk benchmark doesn't use pipelining, which I guess is why we never optimise for it.

When pipelining, doing the read before flushing should be the fastest option, because we might be able to send two replies in a single packet that way. On the other hand, flushing first will be slightly faster when not pipelining and provides some back-pressure, so this PR seems fine to me (but it's good to document the reason - the current changelog makes it sound like a bug fix).

**Comment by bikallem** [comment]
I have added optional parameter `pipeline_requests` to `Client.get/post/head/delete/put/patch/call`. The default value is [false] which means it is optimized by default for individual request/response, i.e. calls `Buf_write.flush()` after each call. I have also updated API doc and change log.

**Comment by bikallem** [comment]
@mseri @talex5 Is there anything outstanding with this PR? If not could we merge this please.

**Comment by mseri** [comment]
I think it can be merged

**Comment by bikallem** [comment]
Thanks.

**Pull request merged**
