### PR TITLE
Improve handling of list valued headers

### PR DESCRIPTION
**Pull request by rgrinberg**
Use a hashtable to check if a header key is list valued rather than a
map

### CODE REVIEW

**Comment by avsm** [comment]
@dsheets, happy with this?  Looks ok to me but deferring to 0.16.0

**Comment by dsheets** [comment]
Does this actually work? We should have test coverage for this... but we probably don't.

Immediately, I don't see where the hash table is initialized with the contents of the list-valued headers.

**Comment by avsm** [comment]
Woops, I thought that happened in the Hashtbl.create section, but it doesn't.

**Comment by rgrinberg** [comment]
@dsheets agreed :confused: i'll fix this and add some tests as well

**Comment by rgrinberg** [comment]
@avsm I've added a (passing) test.

Note that we are getting back the header values in reverse order as we've added them which could be surprising to users.

**Comment by dsheets** [comment]
The order probably matters for some of the headers... I don't know which and I don't know which direction (or if they're even homogeneous). We should probably do a header research/RFC dive to see if the order is specified somewhere.

**Comment by dsheets** [comment]
Actually, I know the order matters for `Accept`. Dunno which way it is supposed to be when there are dupes, though.

**Comment by rgrinberg** [comment]
Unfortunately, I don't much about this subtleties. I'll check out how HTTP is done in other languages. As a first step however, I don't really like how `Header.add` leaves the order up in the air like that. The user should be able to construct a list valued header by providing a list of values.

That being said, this patches does not change the ordering in any way. So perhaps we should create a new issue for this.

**Comment by rgrinberg** [comment]
@avsm the travis failure should be fixed by #261 right?

**Comment by avsm** [comment]
yep.

**Comment by rgrinberg** [comment]
Rebased to rerun travis

**Pull request merged**
