### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by dinosaure**
Assume that #692 is merged, this is a simple commit which update documentations and `README.md` according the new version of `conduit`.

### CODE REVIEW

**Comment by mseri** [comment]
Thanks!

**Comment by dinosaure** [comment]
Documentation is updated as well and I added an example to _extend_ the `ctx` in the `Net` module.

**Comment by mseri** [comment]
Can you please rebase the documentation on master?

**Comment by dinosaure** [comment]
Rebased 👍

**Pull request merged**
