### PR TITLE
Handle empty cookie components gracefully

### PR DESCRIPTION
**Pull request by martinslota**

### CODE REVIEW

**Comment by avsm** [comment]
Thanks! This looks right to me.  Did you run into these malformed cookies in the wild?

**Comment by Leonidas-from-XIV** [comment]
@avsm Yes, we did, unfortunately.

**Comment by avsm** [comment]
Thanks for the PR! I'll cut a quick release.

**Comment by Leonidas-from-XIV** [comment]
Thanks @avsm, much appreciated!

**Pull request merged**
