### PR TITLE
Add dune-lint job to GitHub Actions workflow

### PR DESCRIPTION
**Pull request by smorimoto**
As the title says. And now pin and depext are now performed automatically.

### CODE REVIEW

**Review by mseri — APPROVED** [review]

**Comment by smorimoto** [comment]
It's a little less obvious, but it's done in the post step.
image

**Comment by mseri** [comment]
I think it's nice that it does not clutter the environment if it succeeds, and if it fails we will see that from the action panel

**Comment by smorimoto** [comment]
I'm doing this because there is no smarter way than this at the moment, but I'm glad you felt like that.

**Comment by samoht** [comment]
It's already done in https://ci.ocamllabs.io/github/mirage/ocaml-cohttp/commit/ea53c63339cedaf2bf77878f9eaa34034fc9032b/variant/(lint-opam), why do we need to duplicate it in Github Actions?

**Comment by smorimoto** [comment]
There is no serious reason to duplicate this. For now, this is just some kind of test for the next major release of setup-ocaml, so we can choose not to add this. (I'm testing it on my fork.)

**Comment by samoht** [comment]
Ha nice :-) btw, the Github Actions plugin is very nice, great job!

**Comment by smorimoto** [comment]
Thank you! OCaml CI is really cool and fast enough, but I believe GitHub Actions is a good option for the regular user. Our goal is to allow as many users to use it and test it on many platforms without huge effort. The next major version also includes official container support, so we can test on more platforms such as Alpine and CentOS that are not provided natively by GitHub!

```yml
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        container:
          - debian:latest
          - ubuntu:latest
        ocaml-version:
          - 4.11.x

    runs-on: ubuntu-latest

    container:
      image: ${{ matrix.container }}

    steps:
      - run: apt update && apt install --yes bubblewrap curl darcs gcc git m4 make mercurial patch rsync sudo unzip

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: actions-ml/setup-ocaml@master
        with:
          ocaml-version: ${{ matrix.ocaml-version }}
          opam-disable-sandboxing: true

      - run: ...
```

**Comment by smorimoto** [comment]
I'm rethinking this interface a bit, so I close it once.

**Pull request closed without merging**
