### PR TITLE
Move tests

### PR DESCRIPTION
**Pull request by mseri**
to make the CI happier and greener. Should fix https://github.com/mirage/ocaml-cohttp/issues/708

### CODE REVIEW

**Comment by mseri** [comment]
I don't understand how to deal with this failure:
```
test_async_integration alias cohttp-async/test/runtest (exit 2)
#18 6.207 (cd _build/default/cohttp-async/test && ./test_async_integration.exe)
#18 6.207 Uncaught exception:
#18 6.207   
#18 6.207   (Sys_error "/etc/localtime: No such file or directory")
#18 6.207 
#18 6.207 Raised by primitive operation at file "stdlib.ml", line 398, characters 28-54
#18 6.207 Called from file "src/zone.ml", line 348, characters 21-49
#18 6.207 Called from file "src/timezone.ml", line 142, characters 8-75
#18 6.207 Called from file "camlinternalLazy.ml", line 31, characters 17-27
#18 6.207 Re-raised at file "camlinternalLazy.ml", line 36, characters 4-11
#18 6.207 Called from file "src/core_time_ns.ml", line 462, characters 38-56
#18 6.207 Called from file "src/raw_scheduler.ml", line 895, characters 41-69
#18 6.207 Called from file "cohttp-async/test/test_async_integration.ml", line 122, characters 21-49
```

That is not even a part of the code that I touched...

**Comment by dinosaure** [comment]
Yes, I got several times this error, let me check tomorrow what I did to handle it. However, `core` has a bug on PPC64.

**Comment by dinosaure** [comment]
The real issue is here: https://ci.ocamllabs.io/github/mirage/ocaml-cohttp/commit/3da2402aec5bfc33b92a63d8a4190eecfc462765/variant/centos-8-ocaml-4.10

Then, `core` wants to print the error and while the printing, it wants to access to `/etc/localtime` ... This error is about a flaky tests. I did a small fix in #692 - let me see to re-integrate in this PR.

**Comment by dinosaure** [comment]
The last error about PPC64 is due to core which can not compile on this platform (but should). For me, this PR is ready to merge.

**Comment by mseri** [comment]
Thank you very much for the review. It is a pity that we cannot a still have a green tick. At least I hope this will help us triaging faster the PRs

**Comment by avsm** [comment]
This core issue sounds like it should be constrained in opam-repository -- then it'll be green as that platform wont be selected by ocaml-ci.

**Comment by avsm** [comment]
https://github.com/ocaml/opam-repository/pull/17119

**Comment by mseri** [comment]
Thanks! Then I'll say, let's merge!

**Pull request merged**
