### PR TITLE
Redo IO layer [WIP]

### PR DESCRIPTION
**Pull request by rgrinberg**
tl;dr: Separate IO from parsing.

The goals are:

* Make things like #396 easy
* Remove code duplication that we had in the previous `*_io` modules.
* Testing the parsers should be much easier than it currently is
* Address #242

### CODE REVIEW

**Comment by avsm** [comment]
I like this, but it really will break existing consumers of Cohttp badly. Should we just cut a 1.0 from the 0.19.x base and dive straight into a Cohttp 2.0 with this?

**Comment by rgrinberg** [comment]
Why should it break existing consumers badly? This is barely breaking mirage-http...

At this point the only thing it will break is ocaml-git which should be trivially fixable.

**Comment by avsm** [comment]
> Why should it break existing consumers badly? This is barely breaking mirage-http

Was thinking of the fd-passing byte-by-byte reading version of Cohttp that @djs55 have in XenAPI. It might survive this reasonably actually...

The size limit is now the `string` size limit, isn't it? (just did a quick scan of the patch, will read properly tomorrow)

**Comment by rgrinberg** [comment]
Yeah the size limit is 16k by default. The goal is to have some sort of rudimentary ddos protection from overly massive headers.

**Comment by samoht** [comment]
> At this point the only thing it will break is ocaml-git which should be trivially fixable.

I'm happy to fix it if we have a nicer cohttp API ;-)

**Comment by rgrinberg** [comment]
Cleaned up the commit history a little to make it easier to read.

**Pull request closed without merging**
