### PR TITLE
Fix descriptor leak on thread cancellation for the Lwt client

### PR DESCRIPTION
**Pull request by rgrinberg**
@hcarty small tweak to your revision

### CODE REVIEW

**Comment by hcarty** [comment]
Makes sense, thanks!

**Comment by edwintorok** [comment]
I get `Lwt_io.Channel_closed("input")` when reading the body of a response now, reverting this commit makes the exception go away.
It would seem it calls closefn too eagerly now, before the body was fully read.

**Comment by hcarty** [comment]
Ah @edwintorok I see why `Lwt.on_termination` is a problem now.

Maybe both `Lwt.on_cancel` and `Lwt.on_failure` should be called instead of `Lwt.on_termination`?  I can submit a new PR with that change.

**Comment by hcarty** [comment]
Using `on_cancel` and `on_failure` seems to appease both test cases.  I'll submit a new PR.

**Pull request merged**
