### PR TITLE
Simplify cohttp-lwt-jsoo

### PR DESCRIPTION
**Pull request by mseri**
I was trying to use the package and found rather confusing that one does not use Cohttp_lwt_jsoo and instead uses Cohttp_lwt_xhr.

The documentation already makes it clear that the module uses an XHR request, so I don't really see the need for this discrepancy.

With the upcoming cohttp 3.0 breakage, I think it is worth adding this other small breaking change.

Signed-off-by: Marcello Seri <marcello.seri@gmail.com>

### CODE REVIEW

**Comment by mseri** [comment]
I don't really know who is using this package, so I am not sure whom to pin...

**Review by dinosaure — APPROVED** [review]
LGTM for me.

**Review by avsm — APPROVED** [review]
Good idea! The only other user I'm aware of is the github-jsoo package, but it's easy to adapt the code of course.   A note in the CHANGES file about this would be great.

**Comment by mseri** [comment]
Done. I have updated CHANGES with all the changes since the last release. Thanks

**Pull request merged**
