### PR TITLE
fix(bytebuffer): stripping \r correctly

### PR DESCRIPTION
**Pull request by rgrinberg**
fix the slow path for reading lines to strip \r correctly

cc @anuragsoni

### CODE REVIEW

**Comment by anuragsoni** [comment]
Is `\r` a valid usecase to support for cohttp? I assumed that for what we use the bytebuffer for if we don't have a full `\r\n` then its an error?

**Comment by rgrinberg** [comment]
> Is \r a valid usecase to support for cohttp? I assumed that for what we use the bytebuffer for if we don't have a full \r\n then its an error?

Do you mean just a `\n`? I don't think we handle `\r`

**Comment by anuragsoni** [comment]
I was thinking about the usecase `foobar\r`. In this scenario the read_line attempts to look for a `\n` and since it doesn't find it and we reach an EOF it just responds with the entire unconsumed payload. I'm not sure if stripping the `\r` is worth it here. I'd understand if we strip `\n` or `\r\n`, but stripping just `\r` seems wrong?

**Comment by rgrinberg** [comment]
Ah yes, that was an accident. It's now fixed.

Btw, should we make the `\r` mandatory? I think it's required by the spec in all cases.

**Comment by anuragsoni** [comment]
> Btw, should we make the `\r` mandatory? I think it's required by the spec in all cases.

It is indeed mandatory according to the RFC https://datatracker.ietf.org/doc/html/rfc7230#section-3 I'd be in favor of enforcing CRLF, and treating an LF alone as an error.

**Review by mseri — APPROVED** [review]

**Comment by mseri** [comment]
Should we document this in the CHANGELOG?

**Comment by rgrinberg** [comment]
> Should we document this in the CHANGELOG?

Indeed we should. Although this PR doesn't change this behavior yet. I'll make the change in a subsequent PR.

**Pull request merged**
