### PR TITLE
refactor: remove jsonm as build dependency

### PR DESCRIPTION
**Pull request by rgrinberg**
we now generate the codes and promote them.
to regenerate, run $ dune build @codes

### CODE REVIEW

**Comment by mseri** [comment]
The script still requires jsonm and makes the build fail

**Comment by rgrinberg** [comment]
I'll add jsonm as a test dependency for CI

**Comment by rgrinberg** [comment]
The only thing that fails is the fmt check. I'll try to think of a workaround.

**Comment by mseri** [comment]
We could make the script become an actual test, which fails if the generated file differs from the one that is already there.
Then both lints would succeed, and we have an extra check that we are shipping the right codes

**Comment by rgrinberg** [comment]
Sure, I can do that but it's not the problem. The problem is that ocaml-ci doesn't install the test dependencies to run `@fmt`. @kit-ty-kate any way to configure this?

**Comment by kit-ty-kate** [comment]
I’m not an ocaml-ci maintainer. cc @talex5 @tmcgilchrist

**Comment by mseri** [comment]
I see, indeed it succeeds everywhere else

**Comment by rgrinberg** [comment]
On second thought, how about we just get rid of this script? http isn't changing very often, we don't need the flexibility of generating a few dozen constructors.

**Comment by mseri** [comment]
Fine but then let's put it on a gist, and add a README pointing at it so that we don't have to reinvent the wheel in the rare case we need to update it

**Comment by rgrinberg** [comment]
You mean the script? It will always be present in the git history.

**Comment by mseri** [comment]
I thought you merged this, why did you close it instead?

**Comment by rgrinberg** [comment]
It was folded into the http package pr

**Pull request closed without merging**
