### PR TITLE
cohttp-eio: Match body encoding with headers.

### PR DESCRIPTION
**Pull request by mefyl**
Based on #1011.

### CODE REVIEW

**Review by mseri — APPROVED** [review]

**Comment by mseri** [comment]
Sorry can you rebase on master?

**Comment by mseri** [comment]
And thanks!

**Comment by mseri** [comment]
Thanks

**Comment by mseri** [comment]
I plan to make the release as soon as I figure out why I get the weird failure: https://github.com/mirage/ocaml-cohttp/issues/1010
But I don't have time to look again into it before a couple of weeks

**Comment by mefyl** [comment]
> I plan to make the release as soon as I figure out why I get the weird failure: #1010 But I don't have time to look again into it before a couple of weeks

I think #1013 fixes it.

**Pull request merged**
