### PR TITLE
Small tweaks to the lwt backend

### PR DESCRIPTION
**Pull request by rgrinberg**
I hope this code wasn't inlined on purpose :D

### CODE REVIEW

**Comment by rgrinberg** [comment]
The last commit can hypothetically break compatibility for some.

**Comment by rgrinberg** [comment]
False alarm from travis.

**Comment by rgrinberg** [comment]
The last commit also break compatibility in "theory" because IO is not part of our stable interface.

**Comment by rgrinberg** [comment]
FYI @samoht @avsm 

* IO.iter will be gone
* Client.IO will be gone

**Comment by avsm** [comment]
mainly need to check that mirage-http will be ok

**Comment by rgrinberg** [comment]
@avsm I checked mirage-http and it's ok. Don't remove iter from mirage-http yet though (keep it compatible with older cohttp's as well)

**Comment by avsm** [comment]
lgtm!

**Pull request merged**
