### PR TITLE
Switch to pa_*_conv packages

### PR DESCRIPTION
**Pull request by rgrinberg**
Like https://github.com/mirage/ocaml-conduit/pull/124

cc @dsheets @avsm

### CODE REVIEW

**Comment by rgrinberg** [comment]
Looks like oasis is making this impossible somehow. Passing in `pa_{fields,sex}_conv` also doesn't work for some reason. Oasis doesn't make ocamlbuild enable `-syntax camlp4o`

**Comment by rgrinberg** [comment]
@edwintorok @Drup Any idea why oasis is acting up here?

**Comment by edwintorok** [comment]
On lack of `-syntax camlp4o` from the oasis manual: "automatic inclusion of -syntax camlp4o for packages that matches the internal heuristic (if a dependency ends with a .syntax or is a well known syntax)."
However adding a package with `.syntax` still doesn't work:
```
ocamlopt.opt: don't know what to do with /home/edwin/.opam/async/lib/pa_fields_conv/-ignore.
```

**Comment by rgrinberg** [comment]
Yup. And you can't add `true: syntax(camlp4o)` to the `_tags` file either. Stuck in a bind here.

**Pull request merged**
