### PR TITLE
Closes #225

### PR DESCRIPTION
**Pull request by rgrinberg**

### CODE REVIEW

**Comment by rgrinberg** [comment]
@Chris00 i took your PR and regenerated the oasis files. What's the cause of this failure?

**Comment by Chris00** [comment]
It says ``ocamlfind: Package `conduit.async' not found`` which is strange.  Can you reproduce it on your machine?  On mine
```
$ ocamlfind query conduit.async
/home/chris/.opam/system/lib/conduit
```
and cohttp compiles fine.

**Comment by rgrinberg** [comment]
Seems to work fine for me as well.

**Comment by avsm** [comment]
I think this is because of the addition of constraints in the _oasis file.  It seems to generate different (and buggy) code in that case.

**Comment by Chris00** [comment]
@gildor478 ?

**Comment by gildor478** [comment]
@Chris00 I acknowledge the problem, and it seems related to oasis 0.4.5. The bug seems to not be present in 0.4.4.

Can you generate a minimal _oasis file with those constraint so that I can check and create a test ?

**Comment by gildor478** [comment]
(and followup on:
https://forge.ocamlcore.org/tracker/index.php?func=detail&aid=1447&group_id=54&atid=291 )

**Pull request merged**
