### PR TITLE
avoid reader/writer leaks

### PR DESCRIPTION
**Pull request by vbmithr**
To be merged on Core/Async's official release. I don't think this will compile with released versions.

### CODE REVIEW

**Comment by rgrinberg** [comment]
Why is it necessary to use new async features just to avoid leaks? Can't you back port whatever fix you've made to the old API?

**Comment by rgrinberg** [comment]
Status on this @vbmithr a few words on what the leak is would really help :)

**Comment by vbmithr** [comment]
Let me go through this again.

**Comment by mseri** [comment]
Closing, there have been multiple changes going on in that area.
Feel free to update and reopen it if the leak is still there and you have a fix, make sure to include an explanation of what happens and why please

**Pull request closed without merging**
